/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaulasem2.ventanas;

/**
 *
 * @author 123cr
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        itemRegistrarC = new javax.swing.JMenuItem();
        itemListarC = new javax.swing.JMenuItem();
        itemModificarC = new javax.swing.JMenuItem();
        itemEliminarC = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenu();
        itemRegistrarP = new javax.swing.JMenuItem();
        itemListarP = new javax.swing.JMenuItem();
        itemModificarP = new javax.swing.JMenuItem();
        itemEliminarP = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        itemRegistrarV = new javax.swing.JMenuItem();
        itemListarV = new javax.swing.JMenuItem();
        itemModificarV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        itemRegistrarC.setText("Registrar Cliente...");
        itemRegistrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarCActionPerformed(evt);
            }
        });
        menuCliente.add(itemRegistrarC);

        itemListarC.setText(" Listar Clientes...");
        itemListarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarCActionPerformed(evt);
            }
        });
        menuCliente.add(itemListarC);

        itemModificarC.setText("Modificar Cliente...");
        itemModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarCActionPerformed(evt);
            }
        });
        menuCliente.add(itemModificarC);

        itemEliminarC.setText("Eliminar Cliente...");
        menuCliente.add(itemEliminarC);

        barraMenu.add(menuCliente);

        menuProducto.setText(" Producto");

        itemRegistrarP.setText(" Registrar Producto...");
        itemRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarPActionPerformed(evt);
            }
        });
        menuProducto.add(itemRegistrarP);

        itemListarP.setText(" Listar Productos...");
        menuProducto.add(itemListarP);

        itemModificarP.setText("Modificar Producto...");
        menuProducto.add(itemModificarP);

        itemEliminarP.setText("Eliminar Producto...");
        itemEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarPActionPerformed(evt);
            }
        });
        menuProducto.add(itemEliminarP);

        barraMenu.add(menuProducto);

        menuVenta.setText("Venta");

        itemRegistrarV.setText("Registrar Venta...");
        menuVenta.add(itemRegistrarV);

        itemListarV.setText(" Listar Ventas...");
        menuVenta.add(itemListarV);

        itemModificarV.setText("Modificar Venta...");
        menuVenta.add(itemModificarV);

        barraMenu.add(menuVenta);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEliminarPActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClienteActionPerformed

    private void itemRegistrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarCActionPerformed
        VentanaCliente ventana = new VentanaCliente(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemRegistrarCActionPerformed

    private void itemModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemModificarCActionPerformed

    private void itemListarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemListarCActionPerformed

    private void itemRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarPActionPerformed
        VentanaProducto VentanaProd = new VentanaProducto();
        VentanaProd.setLocationRelativeTo(this);
        VentanaProd.setVisible(true);
    }//GEN-LAST:event_itemRegistrarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemEliminarC;
    private javax.swing.JMenuItem itemEliminarP;
    private javax.swing.JMenuItem itemListarC;
    private javax.swing.JMenuItem itemListarP;
    private javax.swing.JMenuItem itemListarV;
    private javax.swing.JMenuItem itemModificarC;
    private javax.swing.JMenuItem itemModificarP;
    private javax.swing.JMenuItem itemModificarV;
    private javax.swing.JMenuItem itemRegistrarC;
    private javax.swing.JMenuItem itemRegistrarP;
    private javax.swing.JMenuItem itemRegistrarV;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuProducto;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables
}
