/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaulasem2.ventanas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectoaulasem2.bd.Almacenamiento;
import proyectoaulasem2.bd.AlmacenamientoG;
import proyectoaulasem2.bd.AlmacenamientoP;
import proyectoaulasem2.datos.Cliente;
import proyectoaulasem2.datos.Gasto;
import proyectoaulasem2.datos.Producto;

/**
 *
 * @author 123cr
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        itemRegistrarC = new javax.swing.JMenuItem();
        itemListarC = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenu();
        itemRegistrarP = new javax.swing.JMenuItem();
        itemListarP = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        itemRegistrarV = new javax.swing.JMenuItem();
        itemListarV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/Captura de pantalla 2023-10-28 191352.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 400, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/Captura de pantalla 2023-11-21 171138.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 430, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/WhatsApp Image 2023-11-21 at 4.58.05 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/servicio-al-cliente.png"))); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        itemRegistrarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/Gestion.png"))); // NOI18N
        itemRegistrarC.setText(" Gestion de clientes...");
        itemRegistrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarCActionPerformed(evt);
            }
        });
        menuCliente.add(itemRegistrarC);

        itemListarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/List.png"))); // NOI18N
        itemListarC.setText(" Listar Clientes...");
        itemListarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarCActionPerformed(evt);
            }
        });
        menuCliente.add(itemListarC);

        barraMenu.add(menuCliente);

        menuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/estar.png"))); // NOI18N
        menuProducto.setText(" Producto");
        menuProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        itemRegistrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/Gestion.png"))); // NOI18N
        itemRegistrarP.setText(" Gestion de productos...");
        itemRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarPActionPerformed(evt);
            }
        });
        menuProducto.add(itemRegistrarP);

        itemListarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/List.png"))); // NOI18N
        itemListarP.setText(" Listar Productos...");
        itemListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarPActionPerformed(evt);
            }
        });
        menuProducto.add(itemListarP);

        barraMenu.add(menuProducto);

        menuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/carrito.png"))); // NOI18N
        menuVenta.setText("Venta");
        menuVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        itemRegistrarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/Gestion.png"))); // NOI18N
        itemRegistrarV.setText(" Gestion de ventas...");
        itemRegistrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarVActionPerformed(evt);
            }
        });
        menuVenta.add(itemRegistrarV);

        itemListarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoaulasem2/ventanas/iconos/List.png"))); // NOI18N
        itemListarV.setText(" Listar Ventas...");
        itemListarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarVActionPerformed(evt);
            }
        });
        menuVenta.add(itemListarV);

        barraMenu.add(menuVenta);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClienteActionPerformed

    private void itemRegistrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarCActionPerformed
        VentanaCliente ventana = new VentanaCliente(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemRegistrarCActionPerformed

    private void itemListarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCActionPerformed
         if(Cliente.ClientesBD == null || Cliente.ClientesBD.isEmpty()){
            JOptionPane.showMessageDialog(this, "No existen clientes en la BD", "INFORME", JOptionPane.WARNING_MESSAGE);
            return ; 
         }
        VentanaClienteListar ventana = new VentanaClienteListar(this, true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemListarCActionPerformed

    private void itemRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarPActionPerformed
VentanaProductoD v = new VentanaProductoD(this,true);
v.setLocationRelativeTo(null);
v.setVisible(true);

    }//GEN-LAST:event_itemRegistrarPActionPerformed

    private void itemListarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarPActionPerformed
         if(Producto.ProductosBD == null || Producto.ProductosBD.isEmpty()){
            JOptionPane.showMessageDialog(this, "No existen Productos en la BD", "INFORME", JOptionPane.WARNING_MESSAGE);
            return ; 
         }


        VentanaProductoListar v = new VentanaProductoListar(this, true);
        v.setLocationRelativeTo(null);
        v.setVisible(true);
    }//GEN-LAST:event_itemListarPActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Producto.ProductosBD = AlmacenamientoP.retornar();
            Cliente.ClientesBD = Almacenamiento.recuperar();
            Gasto.GastosBD = AlmacenamientoG.retornar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void itemRegistrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarVActionPerformed
       VentanaGastos g = new VentanaGastos(this,true);
       g.setLocationRelativeTo(null);
       g.setVisible(true);
        
    }//GEN-LAST:event_itemRegistrarVActionPerformed

    private void itemListarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarVActionPerformed
                 if(Gasto.GastosBD == null || Gasto.GastosBD.isEmpty()){
            JOptionPane.showMessageDialog(this, "No existen Ventas en la BD", "INFORME", JOptionPane.WARNING_MESSAGE);
            return ; 
         }


        VentanaGastoListar v = new VentanaGastoListar(this, true);
        v.setLocationRelativeTo(null);
        v.setVisible(true);
              
    }//GEN-LAST:event_itemListarVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemListarC;
    private javax.swing.JMenuItem itemListarP;
    private javax.swing.JMenuItem itemListarV;
    private javax.swing.JMenuItem itemRegistrarC;
    private javax.swing.JMenuItem itemRegistrarP;
    private javax.swing.JMenuItem itemRegistrarV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuProducto;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables
}
